const pthsiQuery = `
  pthsi_1 int NOT NULL,
  pthsi_2 int NOT NULL,
  pthsi_3 int NOT NULL,
  pthsi_4 int NOT NULL,
  pthsi_5 int NOT NULL,
  pthsi_6 int NOT NULL,
  pthsi_7 int NOT NULL,
  pthsi_8 int NOT NULL,
  pthsi_9 int NOT NULL,
  pthsi_10 int NOT NULL,
  pthsi_11 int NOT NULL,
  pthsi_12 int NOT NULL,
  pthsi_13 int NOT NULL,
  pthsi_14 int NOT NULL,
  pthsi_15 int NOT NULL,
  pthsi_16 int NOT NULL,
  pthsi_17 int NOT NULL,
  pthsi_18 int NOT NULL,
  pthsi_19 int NOT NULL,
  pthsi_20 int NOT NULL,
  pthsi_21 int NOT NULL,
  pthsi_22 int NOT NULL,
  pthsi_23 int NOT NULL,
  pthsi_24 int NOT NULL,
  pthsi_25 int NOT NULL,
  pthsi_26 int NOT NULL,
  pthsi_27 int NOT NULL,
  pthsi_28 int NOT NULL,
  pthsi_29 int NOT NULL,
  pthsi_30 int NOT NULL,
  pthsi_31 int NOT NULL,
  pthsi_32 int NOT NULL,
  pthsi_33 int NOT NULL,
  pthsi_34 int NOT NULL,
`;

module.exports = pthsiQuery;
