const pedsql57 = {
  name: 'pedsql_5_7',
  query: `
    pedsql_1_0 int NOT NULL,
    pedsql_1_1 int NOT NULL,
    pedsql_1_2 int NOT NULL,
    pedsql_1_3 int NOT NULL,
    pedsql_1_4 int NOT NULL,
    pedsql_1_5 int NOT NULL,
    pedsql_1_6 int NOT NULL,
    pedsql_1_7 int NOT NULL,
    pedsql_2_0 int NOT NULL,
    pedsql_2_1 int NOT NULL,
    pedsql_2_2 int NOT NULL,
    pedsql_2_3 int NOT NULL,
    pedsql_2_4 int NOT NULL,
    pedsql_3_0 int NOT NULL,
    pedsql_3_1 int NOT NULL,
    pedsql_3_2 int NOT NULL,
    pedsql_3_3 int NOT NULL,
    pedsql_3_4 int NOT NULL,
    pedsql_4_0 int NOT NULL,
    pedsql_4_1 int NOT NULL,
    pedsql_4_2 int NOT NULL,
    pedsql_4_3 int NOT NULL,
    pedsql_4_4 int NOT NULL,
  `,
};

module.exports = pedsql57;
